version: '3.3'
services:
   dynamodb-local:
     command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./"
     image: "amazon/dynamodb-local:latest"
     container_name: dynamodb-local
     ports:
       - "8000:8000"
     volumes:
       - "./docker/dynamodb:/home/dynamodblocal/data"
     working_dir: /home/dynamodblocal

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.66.68.0/24
